### ISSUE TITLE
Undefined symbol: ___builtin___clear_cache

### ISSUE THREAD

**Issue by rhdtownsend** [iains/gcc-darwin-arm64#33]
A number of my Fortran codes (but not all) fail to link, because the symbol ___builtin___clear_cache is undefined. 

I'll see if I can concoct a MWE -- but in the meantime, is there anything obvious I'm doing wrong?

**Comment by iains** [comment]
___builtin___clear_cache should end up as a call to a system function (or to a libgcc __clear_cache) .. 
.. it would be interesting to know what causes the builtin to be fired (given that we don't use the stack trampoline, I am not sure what would be calling the cache clear).

**Comment by iains** [comment]
.. so, no, I can't think of anything "obvious" off the top of my head :)

**Comment by rhdtownsend** [comment]
Here's a MWE:

```
module cache_test_m

  implicit none

contains

  function func_a (x)
    real, intent(in) :: x
    real             :: func_a
    func_a = func_c(func_b)
  contains
    function func_b ()
      real :: func_b
      func_b = x
    end function func_b
  end function func_a

  function func_c (func)
    interface
       function func ()
         real :: func
       end function func
    end interface
    real :: func_c
  end function func_c

end module cache_test_m

!****

program cache_test
  use cache_test_m
  implicit none
end program cache_test
```

The missing symbol error arises at -O1 or above; at -O0 there is no problem. It seems the trigger is the host-associated access to the variable `x` in `func_b`.

**Comment by iains** [comment]
Thanks for that, but (using the current branch here) this doesn't fail to link for me (for any -O0..3,s)

Is your build exactly from these sources ? .. how was it configured / built ?

**Comment by rhdtownsend** [comment]
I'm guessing I may have been using a slightly older commit -- although I can't be sure exactly which one. In any case, trying to build from the current head (f51f1da), I get the following failure:

```
Configuring stage 1 in ./libcody
configure: creating cache ./config.cache
checking build system type... aarch64-apple-darwin20.2.0
checking host system type... aarch64-apple-darwin20.2.0
checking number of CPUs... 8
checking maintainer-mode... 
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=c++11 accepts -g... yes
checking whether g++ -std=c++11 is for C++11... yes
checking adding -Wl,--no-undefined to linker... no
checking bugurl... github.com/urnathan/libcody
checking exceptions... no
checking for aarch64-apple-darwin20.2.0-ar... ar
checking for doxygen... : NOTdoxygen
checking for aloy... : Joust testsuite missing
configure: updating cache ./config.cache
configure: creating ./config.status
config.status: creating Makefile
config.status: creating gdbinit
config.status: creating dox.cfg
config.status: creating ./Makesub
config.status: creating ./tests/Makesub
config.status: creating config.h
rm -f .gdbinit ; ln -s gdbinit .gdbinit
g++ -std=c++11 -g -fno-enforce-eh-specs -fno-stack-protector -fno-threadsafe-statics -fno-exceptions -fno-rtti -fdebug-prefix-map=../../gcc-darwin-arm64/libcody/= -W -Wall -include config.h -I../../gcc-darwin-arm64/libcody \
	  -MMD -MP -MF buffer.d -c -o buffer.o ../../gcc-darwin-arm64/libcody/buffer.cc
clang: error: unknown argument: '-fno-enforce-eh-specs'
make[3]: *** [buffer.o] Error 1
make[2]: *** [all-stage1-libcody] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [all] Error 2
```

Not sure what do to about this. FYI, my configure invocation is:

```
../gcc-darwin-arm64/configure \
    --build=aarch64-apple-darwin20.2.0 \
    --prefix=/Users/townsend/devel/sdk2-tmp/mesasdk \
    --with-gmp=/Users/townsend/devel/sdk2-tmp/mesasdk \
    --with-mpfr=/Users/townsend/devel/sdk2-tmp/mesasdk \
    --with-mpc=/Users/townsend/devel/sdk2-tmp/mesasdk \
    --enable-languages=c,c++,fortran \
    --disable-multilib --disable-nls --disable-libsanitizer  \
    --with-sysroot=/Users/townsend/devel/sdk2-tmp/mesasdk/sysroot
```

where `/Users/townsend/devel/sdk2-tmp/mesasdk/sysroot` corresponds to the top-level directory of `MacOSX11.1.sdk.tar.xz`

**Comment by iains** [comment]
Ah .. OK.. there might be issues that came up in the modules merges that I didn't see with my build (I use a GCC bootstrap compiler which I cross-built on x86_64, but not recommending that as a general idea).

My weekly rebase would be tomorrow .. under normal circumstances .. but I might not have as much time because of the holidays .. I think that most of the modules merge issues were resolved during the last week .. I'll note here when it's done.

**Comment by rhdtownsend** [comment]
No hurry -- enjoy the holidays!

**Comment by iains** [comment]
rebased onto r11-6339 (https://gcc.gnu.org/g:5b4da2d9e1c29ce0e36b0e4962078987f65c93a6)

... works for me (bootstrapped with GCC) 
... and a smoke test with a non-Ada bootstrap using clang12.

(some new ObjC++ fails, fallout from someone else's work, I fixed them on GCC master, will be in next week's rebase)

**Comment by rhdtownsend** [comment]
Still not working for me; building 6be7a45 with the same flags as above (and with clang as the compiler) leads to the same error.

**Comment by iains** [comment]
I suspect this is the (**_getting rather old!_**) issue with Xcode having an installation which claims to be g++ (and gcc) but which just forward the invocation to clang.  So we have a situation in which we seem to have a "g++" which supports "c++11" (and therefore corresponds to a new enough g++).  However, it's a lie - the g++ that redirects to clang doesn't really _**officially**_  support anything beyond gcc-4.2.1 (of course, one can be lucky - clang does try to be GCC compatible and vice versa).

This is one of the less lucky cases, clang doesn't support the `-fno-enforce-eh-specs` option.

1/ One solution is to be specific to the configuration process - IFF you are bootstrapping with clang, then say so:  `CC=clang CXX=clang++`

2/ libcody could maybe be more defensive about this, I will take a look and maybe suggest a patch to Nathan.

As a matter of interest what's the intent of specifying `--build=aarch64-apple-darwin20.2.0` ? 
with no spec for host or target (which will default to whatever config.guess produces).

3/ `--disable-multilib --disable-nls ` should not be needed (those are the defaults) - actually, I don't think the sanitiser is enabled by default either for the aarch64 port (I have now enabled it for x86_64-apple-darwin20, tho).

4/ I would add `--disable-libstdcxx-pch` since we can't support PCH as things stand.

so.... (assuming there's a requirement of the build to be specified)

```
../gcc-darwin-arm64/configure \
    --build=aarch64-apple-darwin20.2.0 \
    --prefix=/Users/townsend/devel/sdk2-tmp/mesasdk \
    --with-gmp=/Users/townsend/devel/sdk2-tmp/mesasdk \
    --with-mpfr=/Users/townsend/devel/sdk2-tmp/mesasdk \
    --with-mpc=/Users/townsend/devel/sdk2-tmp/mesasdk \
    --enable-languages=c,c++,fortran \
    --disable-libstdcxx-pch --disable-libsanitizer  \
    --with-sysroot=/Users/townsend/devel/sdk2-tmp/mesasdk/sysroot \
  CC=clang CXX=clang++
```

I tend to bootstrap GMP & friends along with the compiler (a) it can discover bootstrap problems (b) I prefer my toolchains to have no external installation deps.  YMMV but, in any event, that ought not to affect the build.

**Comment by rhdtownsend** [comment]
Thanks for the detailed response! 

1/ Specifying clang/clang++ seems to work -- thanks for the suggestion!

2/ I was under the (likely mistaken) impression that host and and target were picked up from build, if they aren't explicitly specified. In any case, my goal is to build a native compiler; should I set all three explicitly?

3/ I have these in there because my higher-level build scripts (see [rhtownsend/sdk2](https://github.com/rhdtownsend/sdk2)) are designed to work on a variety of platforms (some of which do seem to enable nls etc by default).

4/ Thanks for the suggestion about bootstrapping -- you mean rebuilding GMP with the newly built gcc, right?

**Comment by iains** [comment]
> 2/ I was under the (likely mistaken) impression that host and and target were picked up from build, if they aren't explicitly specified. In any case, my goal is to build a native compiler; should I set all three explicitly?

I tend to set all three explicitly, probably to avoid surprises..
... you are probably correct about the process in this case.

> 3/ I have these in there because my higher-level build scripts (see [rhtownsend/sdk2](https://github.com/rhdtownsend/sdk2)) are designed to work on a variety of platforms (some of which do seem to enable nls etc by default).

well, being explicit is good (as mentioned above :) ) ...

> 4/ Thanks for the suggestion about bootstrapping -- you mean rebuilding GMP with the newly built gcc, right?

If you symlink the sources for GMP &friends into the source tree at the root, then  you no longer need to specify any paths for gap etc. they will be found and built along with the compiler.  The expense is a longer build time - the saving is dependencies on shared libs. 

The other alternative is to make a `--disable-shared --enable-static` build of the prerequisites and install that somewhere, and then it's only necessary to do `--with-gmp=/path/to/the/dependencies/install` which will statically link those into the compiler executables - also avoiding the deps. on shared libs.

It might be that you don't care about deps. on shared libs if you're building something with @rpaths &c. so that it's relocatable as a package... but .. most of my test environments are simpler than that.

**Comment by rhdtownsend** [comment]
I am indeed messing with @rpaths etc, but I like the idea of having GMP etc compiled in-tree. If I go this path, I assume they are automatically rebuilt during the bootstrap, right?

**Comment by iains** [comment]
yes, that's correct.

**Comment by rhdtownsend** [comment]
The original undefined symbol problem has now vanished, and so (after a rather circuitous route!) I'm going to close this issue.
